import { Residence } from './types';

export const MOCK_RESIDENCES: Residence[] = [
  {
    id: 'res-1',
    ownerId: 'owner-1',
    title: 'Appartement de Luxe à Ouaga 2000',
    description: 'Magnifique appartement moderne situé dans le quartier chic de Ouaga 2000. Profitez du calme et du confort.',
    type: 'appartement',
    pricePerNight: 45000,
    advancePercentage: 30,
    cleaningFee: 5000,
    serviceFee: 0,
    address: {
      city: 'Ouagadougou',
      neighborhood: 'Ouaga 2000',
      street: 'Avenue du 15 Octobre',
      coordinates: { lat: 12.3714, lng: -1.5197 }
    },
    amenities: ['Wi-Fi', 'Climatisation', 'Parking', 'Sécurité 24/7', 'Piscine'],
    utilitiesIncluded: { water: true, electricity: true },
    pricingTiers: [],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1200'],
    capacity: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rooms: 4,
    rating: 4.8,
    ownerPhone: '+226 70 12 34 56',
    status: 'published',
    availabilityStatus: 'available',
    ownerName: 'Moussa Traoré',
    createdAt: new Date().toISOString()
  },
  {
    id: 'res-2',
    ownerId: 'owner-2',
    title: 'Villa Paisible à Bobo Dioulasso',
    description: 'Une villa spacieuse parfaite pour les séjours en famille ou entre amis à Sya.',
    type: 'villa',
    pricePerNight: 75000,
    advancePercentage: 50,
    cleaningFee: 10000,
    serviceFee: 0,
    address: {
      city: 'Bobo Dioulasso',
      neighborhood: 'Accart-ville',
      street: 'Rue de la Guinguette',
      coordinates: { lat: 11.1858, lng: -4.2959 }
    },
    amenities: ['Wi-Fi', 'Climatisation', 'Cuisine équipée', 'Jardin'],
    utilitiesIncluded: { water: false, electricity: false },
    pricingTiers: [],
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=1200'],
    capacity: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 3,
    rooms: 5,
    rating: 4.5,
    ownerPhone: '+226 71 88 88 88',
    status: 'published',
    availabilityStatus: 'available',
    ownerName: 'Fatoumata Ouédraogo',
    createdAt: new Date().toISOString()
  },
  {
    id: 'res-3',
    ownerId: 'owner-1',
    title: 'Studio Cosy Center Ouaga',
    description: 'Petit studio parfaitement situé au centre-ville pour vos déplacements d\'affaires.',
    type: 'appartement',
    pricePerNight: 25000,
    advancePercentage: 100,
    cleaningFee: 0,
    serviceFee: 0,
    address: {
      city: 'Ouagadougou',
      neighborhood: 'Koulouba',
      street: 'Avenue de la Liberté',
      coordinates: { lat: 12.3686, lng: -1.5271 }
    },
    amenities: ['Wi-Fi', 'Petit-déjeuner inclus', 'Climatisation'],
    utilitiesIncluded: { water: true, electricity: false },
    pricingTiers: [],
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=1200'],
    capacity: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rooms: 2,
    rating: 4.9,
    ownerPhone: '+226 70 12 34 56',
    status: 'published',
    availabilityStatus: 'available',
    ownerName: 'Moussa Traoré',
    createdAt: new Date().toISOString()
  }
];
